-- +goose Up
ALTER TABLE tasks
    ALTER COLUMN id TYPE BIGINT,
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY,
    ALTER COLUMN uuid SET NOT NULL,
    ADD CONSTRAINT tasks_uuid_key UNIQUE (uuid);

-- +goose Down
ALTER TABLE tasks
    DROP CONSTRAINT tasks_uuid_key,
    ALTER COLUMN uuid DROP NOT NULL,
    ALTER COLUMN id DROP IDENTITY,
    ALTER COLUMN id TYPE INT;
